### ISSUE TITLE
Missing security license 

### ISSUE THREAD

**Issue by dmenisdev** [lostintime101/driving_theory_test#4]
First off, fantastic that you made this.

The website is missing SSL, it works but would be much easier to access with SSL 😅.
https://letsencrypt.org/ free SSL could be a good option.

<img width="333" alt="image" src="https://github.com/lostintime101/driving_theory_test/assets/7593391/5224df66-c141-42fa-a442-5de65b8582c6">

PS: if there is anything I can do to help feel free to let me know.

**Comment by lostintime101** [comment]
Hey Dennis, really appreciate the heads up. I've restarted nginx and now the cert has been updated.

**Comment by baptiste-n42** [comment]
Hi guys, thanks Denis for the report :raised_hands: 
I just added a post-renewal hook on the `certbot` configuration to reload nginx automatically when the certificate is renewed.
The current certificate will expire on 29/08/24. I will check if the hook run correctly and I'll let you guys know

**Comment by baptiste-n42** [comment]
Time went by and the certificate has renewed itself without intervention. 
I think @lostintime101 can close this ticket :raised_hands: 
Thanks again for the heads up @dennisvd !
